### ISSUE TITLE
not opening domain from wps namelist

### ISSUE THREAD

**Issue by AbdBaten** [anikfal/PostWRF#22]
Hi,
Hope, you are doing well. I am using NCL v 6.6.2. I have set display environment 0.0 in my bash. Now that when I was trying to figure the domain from the namelist.wps file, I got fatal errors (plz look at the attached file). 
Will appreciate your feedback.
Thanks
Masud Rana
![Screenshot from 2023-10-18 16-48-51](https://github.com/anikfal/PostWRF/assets/142993104/8efb653d-397a-4672-8f35-bcb726cba3ae)

**Comment by anikfal** [comment]
Hi,
From your report, the problem is obvious. You have not provided any WRF output in the PostWRF's directory. Please copy or link your WRF files in PostWRF's directory and then run PostWRF.

Please take a look at the HTML documentations or YouTube training videos:
https://github.com/anikfal/PostWRF#youtube-training-videos

**Comment by AbdBaten** [comment]
Hi Amir Hossain,
Sorry for my late response; after following your suggestion, the software runs very well now.
Thanks
Masud
